### ISSUE TITLE
Performance concern regarding print function

### ISSUE THREAD

**Issue by UE2020** [Alonely0/Voila#2]
The print function does not seem to implement block buffering. So if you print a lot of lines, you end up calling the `write` syscall for every line, which is quite costly.

**Comment by Alonely0** [comment]
false, print function collects all args and then prints them in a single syscall
https://github.com/Alonely0/Voila/blob/d259f22febb442613354f757b45c867ebfcb3f1e/src/interpreter/functions.rs#L61

**Comment by UE2020** [comment]
> false, print function collects all args and then prints them in a single syscall
> 
> https://github.com/Alonely0/Voila/blob/d259f22febb442613354f757b45c867ebfcb3f1e/src/interpreter/functions.rs#L61

Line buffering and block buffering are not the same thing. Rust's `io::stdout` does not do block buffering by default.

https://github.com/rust-lang/rust/issues/60673

**Comment by BlueCannonBall** [comment]
In C, `setvbuf(stdout, NULL, _IOFBF, 0);` can be used to make stdout block buffered. By default, it is line buffered.

**Comment by Alonely0** [comment]
ah lol, didn't know that. Tomorrow I'll patch it

**Comment by Alonely0** [comment]
These are the measures I made:

* stdout lock + write buffer
  ```./target/debug/voila /home/guillem/ "1 == 1 {print(@name: @size=mb)}"  0.05s user 0.01s system 132% cpu 0.046 total```

* stdout + write buffer
  ```./target/debug/voila /home/guillem/ "1 == 1 {print(@name: @size=mb)}" -r  56.35s user 7.84s system 99% cpu 1:04.33 total```

* stdout lock
  ```./target/debug/voila /home/guillem/ "1 == 1 {print(@name: @size=mb)}" -r  54.93s user 8.20s system 99% cpu 1:03.28 total```

* just print args joined
  ```./target/debug/voila /home/guillem/ "1 == 1 {print(@name: @size=mb)}" -r  55.33s user 8.62s system 99% cpu 1:04.14 total```

We have a clear winner.

**Comment by Alonely0** [comment]
https://github.com/Alonely0/Voila/commit/98454e78cff928fa8b0407d53a25ed4950e23324
