### ISSUE TITLE
Add tokio runtime to optimize voila and make it faster

### ISSUE THREAD

**Issue by Alonely0** [Alonely0/Voila#9]
I've been testing Voila execution times using the tokio runtime. These are the results:
* no tokio runtime
   ```
   ➜ time ./target/debug/voila ~ '@name == @name { print(@path) }' -r
    Executed in   80.10 secs    fish           external
      usr time   59.58 secs  600.00 micros   59.58 secs
      sys time   13.80 secs  236.00 micros   13.80 secs
   ```
* tokio runtime initialized on interpreter
   ```
   ➜ time ./target/debug/voila ~ '@name == @name { print(@path) }' -r
    Executed in   65.67 secs    fish           external
      usr time   58.11 secs  551.00 micros   58.11 secs
      sys time    7.39 secs  263.00 micros    7.39 secs
   ```
* tokio runtime initialized on main
   ```
   ➜ time ./target/debug/voila ~ '@name == @name { print(@path) }' -r
    Executed in   64.50 secs    fish           external
      usr time   57.34 secs    0.00 micros   57.34 secs
      sys time    7.01 secs  449.00 micros    7.01 secs
   ```

This issue is for discussing which one should be implemented, if the one that only affects the interpreter, that is where all the async stuff resides, or implement it on all Voila's source by initializing it on main.

**Comment by Alonely0** [comment]
tokio on main awaiting the interpreter seems the best, but I still think that it's a bit of waste because it's only affecting the interpreter, except it all voila code is synchronous

**Comment by CyberGsus** [comment]
could we see a more precise benchmark for this? [Criterion](https://bheisler.github.io/criterion.rs/book/index.html) would be a good tool for that. The issue is, you're measuring the time from exec() to exit(), which includes time that the OS is not actually executing your process or what your process wants (i.e syscalls to get the directory contents).

**Comment by CyberGsus** [comment]
curiously, the tokio main implementation is a lot slower than the rest (around ~300ms) ,looking at the typical and std dev. no tokio has shown the best performance, probably due to rayon. I feel like threads are a better way to go, as async is single threaded

**Comment by Alonely0** [comment]
so should we leave it as it's now, without tokio?

**Comment by Alonely0** [comment]
atm we should
